### ISSUE TITLE
/usr/bin/env more universal than /bin/env

### ISSUE THREAD

**Issue by djbclark** [NMMES/nmmes-cli#1]
/usr/bin/env more universal than /bin/env - specifically MacOS X doesn't have /bin/env

```
$ nmmes
-bash: /usr/local/bin/nmmes: /bin/env: bad interpreter: No such file or directory
```

In general [/bin is just stuff that is 100% needed for booting](http://www.pathname.com/fhs/pub/fhs-2.3.html).

From heavily upvoted answer [over at StackExchange](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my):

> There are two programs whose location you can rely on on almost every unix variant: /bin/sh and /usr/bin/env. Some obscure and mostly retired Unix variants had /bin/env without having  /usr/bin/env, but you're unlikely to encounter them. Modern systems have /usr/bin/env precisely because of its widespread use in shebangs. /usr/bin/env is something you can count on.

**Comment by FallingSnow** [comment]
Got it, will include `/usr/bin/env` in all my projects from now on.
