### ISSUE TITLE
Can't get it installed.

### ISSUE THREAD

**Issue by sixhoursago** [NMMES/nmmes-cli#3]
I use h265ize and keep seeing posts encouraging me to give nmmes-cli a go. However I can't seem to get it installed and working. I keep seeing alerts such as "npm WARN deprecated node-uuid@1.4.8: Use uuid module instead". After it appears to install, running "nmmes-cli" results in "command not found"

¯\_(ツ)_/¯

**Comment by FallingSnow** [comment]
Did you install it with the global option: `npm install --global nmmes-cli`?

**Comment by FallingSnow** [comment]
Oh, lol, the command is `nmmes`.

**Comment by sixhoursago** [comment]
@FallingSnow Aha! So it is installed and working! Thank you. :)
Thanks for making this. I'm eager to see it progress.

The output is a bit noisier than I'm used to. It looks kinda like h265ize in debug mode. Is there a way to quiet it down? Also, I tried the --delete option and it appears to have deleted the test source file without first transcoding it. And it seems to be scoffing at directories containing non-video files like .srt.

¯\_(ツ)_/¯ But that's plenty alright with me for now! Neat to have this working!

**Comment by FallingSnow** [comment]
> The output is a bit noisier than I'm used to. It looks kinda like h265ize in debug mode. Is there a way to quiet it down?

It's broken at the moment so I just default to debug. I think I'm going to have to switch logging libraries so I've been putting it off.

> Also, I tried the --delete option and it appears to have deleted the test source file without first transcoding it.

I will look into this.

> And it seems to be scoffing at directories containing non-video files like .srt.

Scoffing? Like it ignores these directories? In that case that is the intended operation.

**Comment by sixhoursago** [comment]
> Scoffing? Like it ignores these directories? In that case that is the intended operation.

Yep, just like that. Hey I'm cool with intended operation. 👍  This is just me figuring it out. :) Thank you for the help.

**Comment by FallingSnow** [comment]
[I wrote a new logger](https://github.com/NMMES/nmmes-tracer) to fix the logging issues.
