### ISSUE TITLE
Some hard coded paths?

### ISSUE THREAD

**Issue by my95z34** [NMMES/nmmes-cli#4]
Not sure what to name this 'issue', lol.  But I just installed NMMES to toy with, as I've been using h265ize for some time.  When running nmmes --help I get a lot of output, some of it seeming to contain hardcoded paths to your system, @FallingSnow 

```
   at requireModule (C:\Users\Andrew\AppData\Roaming\npm\node_modules\nmmes-cli\dist\nmmes-cli.js:414:22)
    at C:\home\ayrton\Documents\nmmes-cli\src\options.js:170:39

```

Just posting this to let you know!  Thanks, as always, for your hard work.

**Comment by FallingSnow** [comment]
Thanks!

Fixed by https://github.com/NMMES/nmmes-cli/commit/fc2d86a03d8981f8840d0b1a2fc5b67f03b0feb5
