### ISSUE TITLE
PC suspend while encoding.

### ISSUE THREAD

**Issue by MeisterKnobi** [NMMES/nmmes-cli#5]
I started to use nmmes, and as its marked as alpha im not sure how to report the bugs i found. My guess one bug one issue. But when im wrong please let me know how i can help you better.

For this issue atm i just increase the time to suspend, buts thats only a workaround and not the solution i hope.

**Comment by FallingSnow** [comment]
> My guess one bug one issue.

Correct.

> For this issue atm i just increase the time to suspend, buts thats only a workaround and not the solution i hope.

Unfortunately for the foreseeable future this is the solution. Wakelocks are something done with low level access and it does not appear nodejs provides an api for this. What solutions exist do not seem to be very cross platform and do not seem to be maintained.

Wish there was a better solution, sorry.
