### ISSUE TITLE
<ERROR> Cannot read property 'metadata:s:2' of undefined

### ISSUE THREAD

**Issue by Altaesis** [NMMES/nmmes-cli#6]
When running nmmes on my directory every file errors out with the same error. 

```
<LOG> Set title for subtitle stream undefined [0:2] to English (ASS)
<ERROR> Video stopped processing with error: Cannot read property 'metadata:s:2' of undefined
<ERROR> Cannot read property 'metadata:s:2' of undefined
<INFO> Processing queue emptied.
````

**Comment by FallingSnow** [comment]
Please run with `--debug` and post the whole log.

**Comment by Pyrran** [comment]
I've just found your tool and am trying it out, had decent results so far so thank you.  I would love it more if it could optionally create a small "nmmes.results" file in the output folder showing the before and after of that run so you can easily see the overall encoding stats of the file(s) - showing how much saving has been made, encoding time, etc  ;)

Anyway - I have however come across the same problem as the OP.  My log below as requested.

[debug.log](https://github.com/NMMES/nmmes-cli/files/1866196/debug.log)

`

**Comment by FallingSnow** [comment]
Should be fixed now. Please install `nmmes-module-normalize` via `npm install NMMES/nmmes-module-normalize -g` and test again.

@Pyrran Checkout https://github.com/NMMES/nmmes-module-stats. I will try to update the documentation on it today, otherwise you can use `--help` in the meantime.

**Comment by Altaesis** [comment]
I now get this as an error. I've attached logs.
```
<ERROR> Cannot read property 'trace' of undefined
```

[log.log](https://github.com/NMMES/nmmes-cli/files/1866777/log.log)

**Comment by FallingSnow** [comment]
This is because of the change in logging structure that I made to nmmes. You can try installing everything from their git repo to get fall into line. Or I should push out another set of updates soon that you can use.

**Comment by FallingSnow** [comment]
@Seolae Updates have been pushed out, try reinstalling nmmes-cli and the modules you are using.

**Comment by Seolae** [comment]
Will do thanks!
