### ISSUE TITLE
Error at folder processing when path contains spaces

### ISSUE THREAD

**Issue by MeisterKnobi** [NMMES/nmmes-cli#7]
```
<ERROR> UNHANDLED ERROR: { Error: ENOENT: no such file or directory, stat 'M:\Serien\Sherlock (2010)" -d D:\Neu\sherlock --debug'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock --debug' }
<ERROR> UNHANDLED ERROR: { Error: ENOENT: no such file or directory, stat 'M:\Serien\Sherlock (2010)" -d D:\Neu\sherlock --debug'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock --debug' }
<ERROR> UNHANDLED ERROR: { Error: ENOENT: no such file or directory, stat 'M:\Serien\Sherlock (2010)" -d D:\Neu\sherlock --debug'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock --debug' }
```

It only occurs when im trying to process a whol folder, with path contains spaces. No Problems when the File itself contains a spaces. Single Files with spaces in its path are working fine.

**Comment by FallingSnow** [comment]
It looks like it's trying to stat `M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock --debug` when it should be trying to stat `M:\\Serien\\Sherlock (2010)`.

Double check the command you are trying to run and pos the full log.

**Comment by MeisterKnobi** [comment]
Sry for the wait.
the command "nmmes 'M:\Serien\Sherlock (2010)\' -d 'D:\Neu\sherlock'" causes this error: 
`PS C:\Users\user> nmmes 'M:\Serien\Sherlock (2010)\' -d D:\Neu\sherlock
<TRACE> 17:42:43.93 () [options.js:181] Loaded module nmmes-module-normalize.
<TRACE> 17:42:44.38 () [options.js:181] Loaded module nmmes-module-encoder.
<TRACE> 17:42:44.40 () [index.js:123] Options: { _: [ 'M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock' ],
  version: false,
  help: false,
  delete: false,
  watch: false,
  'normalize-audio-titles': true,
  normalizeAudioTitles: true,
  'normalize-subtitle-titles': true,
  normalizeSubtitleTitles: true,
  'normalize-force': false,
  normalizeForce: false,
  'encoder-preview': false,
  encoderPreview: false,
  'encoder-hardware-decoding': false,
  encoderHardwareDecoding: false,
  profile: 'none',
  g: 'C:\\Users\\user\\AppData\\Local\\Temp\\nmmes-cli',
  'temp-directory': 'C:\\Users\\user\\AppData\\Local\\Temp\\nmmes-cli',
  tempDirectory: 'C:\\Users\\user\\AppData\\Local\\Temp\\nmmes-cli',
  d: 'C:\\Users\\user\\nmmes-out',
  destination: 'C:\\Users\\user\\nmmes-out',
  modules: [ 'normalize', 'encoder' ],
  f: 'mkv',
  'output-format': 'mkv',
  outputFormat: 'mkv',
  s: [],
  'skip-video-codec': [],
  skipVideoCodec: [],
  'normalize-language': 'eng',
  normalizeLanguage: 'eng',
  'normalize-scale': 0,
  normalizeScale: 0,
  'normalize-autocrop-intervals': 12,
  normalizeAutocropIntervals: 12,
  'encoder-video-codec': 'libx265',
  encoderVideoCodec: 'libx265',
  'encoder-preset': 'fast',
  encoderPreset: 'fast',
  'encoder-quality': 19,
  encoderQuality: 19,
  'encoder-bitdepth': 0,
  encoderBitdepth: 0,
  '$0': 'AppData\\Roaming\\npm\\node_modules\\nmmes-cli\\dist\\nmmes-cli.js' }
<ERROR> UNHANDLED ERROR: { Error: ENOENT: no such file or directory, stat 'M:\Serien\Sherlock (2010)" -d D:\Neu\sherlock'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock' }
<ERROR> UNHANDLED ERROR: { Error: ENOENT: no such file or directory, stat 'M:\Serien\Sherlock (2010)" -d D:\Neu\sherlock'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock' }
<ERROR> UNHANDLED ERROR: { Error: ENOENT: no such file or directory, stat 'M:\Serien\Sherlock (2010)" -d D:\Neu\sherlock'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'M:\\Serien\\Sherlock (2010)" -d D:\\Neu\\sherlock' }
PS C:\Users\user>`

when i change the foldername from 'Sherlock (2010)' to just 'Sherlock' the command "nmmes 'M:\Serien\Sherlock\' -d 'D:\Neu\sherlock'" its works fine.
I dont think its important, because on local drives its the same problem. M: is a SMB networkdrive.

**Comment by FallingSnow** [comment]
Use ``` when you are trying to wrap large code blocks, I modified your comment above already.

Try `nmmes 'M:\Serien\Sherlock (2010)' -d D:\Neu\sherlock`. I removed the trailing slash on the input directory, it may have been escaping the closing single quote. If that doesn't work try swapping the single quotes to double quotes (").

**Comment by MeisterKnobi** [comment]
> Use ``` when you are trying to wrap large code blocks, I modified your comment above already.

didnt know that trick, i wondered why the code tag has this shitty format. thanks (i edited my first post too)

> I removed the trailing slash on the input directory, it may have been escaping the closing single quote.

uh. it looks like it has fixxed my issue. I was just using the autocomplete funktion from powershell. Seems to be a windows bug only^^

Are you going try to fix it or leave it at the workaroud? Other windows users might run in the same problem as well.

**Comment by FallingSnow** [comment]
> Are you going try to fix it or leave it at the workaroud? Other windows users might run in the same problem as well.

Leave it, if it is actually an issue with Windows (unlikely), that is windows problem. Escaping a character by placing a backward slash in front of it is pretty universal.

It seems strange that Windows would end up escaping the last quote. Are you adding the single quotes yourself?

**Comment by MeisterKnobi** [comment]
No i didnt. Powershell does it by its self. 
For example: you type `D` and press \<TAB\> its autocomplede to `.\Desktop\`
When the foldername contains spaces it wrapps the whole path in single ' quotes like `'.\Desktop New\'`

**Comment by FallingSnow** [comment]
Wow. Amazing.

Well thanks for informing me, I guess Windows has it's own... "special" way of doing things.

At least we identified the issue and a work around so that you can start using nmmes-cli.
